### ISSUE TITLE
Milestone 2 Checklist

### ISSUE THREAD

**Issue by shoebillm** [UBC-MDS/pyeasytries#18]
- [x] **Write test cases and code iteratively**
     - [x] Review function specifications 
     - [x] Write a unit test function for each specified function (`test_functionname`) with 3-5 edge cases (X4)
     - [x] Write the internal code for python functions
     - [x] Update code documentation of functions and tests
     - [x] Exception Handling using `if` & `raise TypeError`
     - [x] Record ideas/notes in issues from Milestone 1 and close by the end of Milestone 2
     - [x] Create an issue for new issue/ideas (optional)

- [x] **R package checklist**
     - [x] Create project structure for the R project
     - [x] README.md (1. summary, 2. function descriptions, 3. how fit into R ecosystem)
     - [x] R package function specifications + docstrings (X4)

- [x] **Submission**
     - [x] URL for each of the public projects' repositories (X2)
     - [x] URL to a release for each of the projects' repositories (X2)

**Comment by rainbowxyt0305** [comment]
Done Milestone 2!
