### ISSUE TITLE
Milestone 3 To-do List

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/pyeasytries#35]
### R package

**Test cases and code iteratively**
- [x] Revisit function specifications and revise if needed (input/return)
- [x] Write unit tests for each function using `testthat` with 3-5 edge cases associated with 2-3 `test_that` code blocks per function (X4)
- [x] Write internal code for R functions (X4)
- [x] Tests cover all branches
- [x] Update documentation (docstrings)
- [x] Check the code passes all tests via `devtools::test()`

**Exception handling**
- [x] Functions written defensively (errors & exceptions)

**Planning & organizing work**
- [x] Record ideas and notes for each function and close issues (X4)
- [x] (Optional) Record new ideas or test cases not yet implemented

### Python package

**GitHub actions workflow for continuous integration**
- [x] Configure `.github/workflows/build.yml` on `main` branch
       - [ ] Ensure the deployment branch (typically the `main` branch) is correctly specified on lines 7 & 10
       - [ ] Ensure that the correct Python version is listed on lines 21 and 24 (it should match the version in your `pyproject.toml` file)

**GitHub actions workflow for continuous deployment**
- [x] Configure `.github/workflows/deploy.yml` on `main` branch
       - [ ] Ensure the deployment branch (typically the `main` branch) is correctly specified on lines 7
       - [ ] Ensure that the correct Python version is listed on line 14 (it should match the version in your `pyproject.toml` file)

**Documentation**
- [x] Clear documentation deployed by ReadTheDocs
- [x] Docstrings rendered using the `napolean` Sphinx (X4)
- [x] Demonstration of how to use each function in the package

### Submission
- [x] The URL for each of your your public projects' repositories (X2)
- [x] The URL to a release for each of your projects' repositories (X2)

**Comment by rainbowxyt0305** [comment]
Done all items!
